### ISSUE TITLE
In bash, put "then"s on a new line separate from the "if"

### ISSUE THREAD

**Issue by exfret** [maxsu/balancers2#11]
From googling (and a headache caused by it not being on a new line causing compilation errors), I've found that this is the standard way of doing things. The "then" was previously on the same line, but I have since fixed the error. I wanted to open an issue on this to make Max aware.

**Comment by maxsu** [comment]
The issue that `if command` is an independent statement, so bash needs a statement separator `;` to parse correctly:

This works:
```
if condition; then
  command
fi

```
This fails:

```
if condition then
  command
fi

bash: syntax error near unexpected token `then'
```

The semicolon separating the if and then statements is the "de facto" standard that you'll see in most bash scripts (since it saves a line).  This is also the standard imposed by the shfmt bash formatter (part of [mvdan/sh](https://github.com/mvdan/sh)), which I use to format sh scripts 

See also:
[this stack overflow question](https://stackoverflow.com/questions/50117346/why-do-some-people-put-a-semicolon-after-an-if-condition-in-shell-scripts)

<details>
 <summary>The output of `help if` in bash</summary>
```
if: if COMMANDS; then COMMANDS; [ elif COMMANDS; then COMMANDS; ]... [ else COMMANDS; ] fi
    Execute commands based on conditional.

    The `if COMMANDS' list is executed.  If its exit status is zero, then the
    `then COMMANDS' list is executed.  Otherwise, each `elif COMMANDS' list is
    executed in turn, and if its exit status is zero, the corresponding
    `then COMMANDS' list is executed and the if command completes.  Otherwise,
    the `else COMMANDS' list is executed, if present.  The exit status of the
    entire construct is the exit status of the last command executed, or zero
    if no condition tested true.

    Exit Status:
    Returns the status of the last command executed.
```
</details>


## Alternate syntax:

#### inline then
```
if condition
  then command
fi
```

There are cleaner formats as well. I am also happy with these syntax for simple if statements:

#### Short circuit conditional (if condition and command are simple)

```
# This executes command if the condition command
#  or function returns a successful status (0): 
condition && command  
```

#### Complex then

Here we split our then statement from the command, and use an extra indent for maximum readability
```
if condition
  then
    command1
    command2
fi
```

These are more readable than standard format in my opinion. Lets pick a standard and stick with it

Pros for the standard (`if condition; then`):
- De facto standard
- `shfmt` does it automatically
Cons:
- Easy to forget the `;` at first
- The `;` is uneccessary line noise

Pros for the cleaner format (if and then on separate lines)
- More readable
- Less error prone
Cons:
- `shfmt` converts this to the traditional standard

I've adopted the standard in my own code, since `shfmt` makes other things so nice.


Proposal 1: Since our shells will be simple, we can use the cleaner format, and manually restore the layout if we use `shfmt` to format other parts of the script

Proposal 2: I can patch `sfmt` to implement the cleaner standard

**Comment by exfret** [comment]
I say we stick by the standard. I wasn't aware of it, and I think it would be best to keep to it. I'd been seeing the other way of writing things, so I assumed that was the standard, but I stand corrected. Does this sound good?

**Comment by maxsu** [comment]
Sounds very good, I'll let you do the honor and close
